version: 1
tasks:
- metadata:
    name: "version-control-tools Tests"
    description: "Builds the test environment and runs tests (without Docker)"
    owner: ${push.owner}
    source: ${repository.url}
  taskId: '${as_slugid("decision")}'
  taskGroupId: '${as_slugid("decision")}'
  schedulerId: '${repository.level}'
  created: {$fromNow: ''}
  deadline: {$fromNow: '1 day'}
  expires: {$fromNow: '1 year 1 second'} # 1 second so artifacts expire first, despite rounding errors
  provisionerId: "aws-provisioner-v1"
  workerType: "version-control-tools"
  scopes: []
  routes:
    - "tc-treeherder.v2.${repository.project}.${push.revision}.${push.pushlog_id}"
  dependencies: []
  requires: all-completed
  retries: 5
  payload:
    env:
      HG_VERSION: "4.6.2"
      NO_DOCKER: 1
      TMPDIR: /work/tmp
      USER: hg
    image: 'mozvct/vcttest:0.4'
    maxRunTime: 3600
    command:
      - "/bin/bash"
      - "-lc"
      - "mkdir /work/tmp && hg clone ${repository.url} /work/vct && cd /work/vct && hg up ${push.revision} && chown -R worker:worker /work && su worker -- testing/taskcluster-run-tests"
  extra:
    treeherder:
      symbol: 4.6
      jobKind: test
      productName: version-control-tools
