---
# We assume in various places in this file that we only run on RHEL/CentOS.
- name: determine if running in Docker
  stat: path=/vct
  register: vct_dir

- name: install epel package repository
  yum: name=epel-release
       state=present

- name: install supervisor
  yum: name=supervisor
       state=present

- name: create supervisor config directory
  file: path=/etc/supervisor.d
        state=directory
        mode=0755
        owner=root
        group=root

- name: install main supervisor config
  copy: src=supervisord.conf
        dest=/etc/supervisord.conf
        owner=root
        group=root
        mode=0644

- name: ensure supervisor service is started
  service: name=supervisord
           state=started
  when: vct_dir.stat.exists == False
