---

# yum will incur network traffic when URLs are specified. Download the
# package locally first so we can run offline after initial bootstrap.

- name: download Mercurial package
  get_url: url=https://s3-us-west-2.amazonaws.com/moz-packages/CentOS7/mercurial-4.8-1.x86_64.rpm
           dest=/var/tmp/mercurial-4.8-1.x86_64.rpm
           sha256sum=1f13e146723ba6a3c542b19d74e7a69d6e52fad2ef285706209a2dc7e91eb89f

- name: Install patch package
  yum: name=patch state=present

- name: installed Mercurial
  yum:
    name: /var/tmp/mercurial-4.8-1.x86_64.rpm
    state: present
