---
# Ansible role to configure a TICK stack monitoring host
- name: download packages for InfluxDB
  get_url:
    dest: /var/tmp/{{ item.package }}
    url: https://dl.influxdata.com/{{ item.program }}/releases/{{ item.package }}
    sha256sum: "{{ item.sha256 }}"
  with_items:
    - { program: influxdb,   package: influxdb-1.7.3.x86_64.rpm,   sha256: 2dc688239fc394a82c4dfaaa6340d438229a8315e21f412a0accf1f0eb700ec4 }
    - { program: chronograf, package: chronograf-1.7.7.x86_64.rpm, sha256: 872a73bc9ad230498c045bddbbde5bff15a27b521084a90cef99f971f227f4be }
    - { program: kapacitor,  package: kapacitor-1.5.2.x86_64.rpm,  sha256: 297ef31572ee9844e5a27d036019afca4c8e0201af096aa0b4ca5c4654fe38ab }

- name: install InfluxDB packages
  yum:
    name: /var/tmp/{{ item }}
    state: present
  with_items:
    - influxdb-1.7.3.x86_64.rpm
    - chronograf-1.7.7.x86_64.rpm
    - kapacitor-1.5.2.x86_64.rpm

- name: start monitoring services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - influxdb
    - chronograf
    - kapacitor

- name: create directory for Kapacitor tasks
  file:
    path: /etc/kapacitor/tasks
    state: directory
    owner: kapacitor
    group: kapacitor
    mode: 0755

- name: move Kapacitor tasks to host
  copy:
    src: "{{ item }}"
    dest: /etc/kapacitor/tasks/{{ item }}
    owner: kapacitor
    group: kapacitor
  with_items:
    - disk_space.tick
    - load.tick
    - vcsreplicator_consumer_lag.tick
    - vcsreplicator_processes.tick

- name: create Kapacitor tasks
  command: /usr/bin/kapacitor define {{ item }} -tick /etc/kapacitor/tasks/{{ item }}.tick -dbrp "telegraf"."autogen"
  with_items:
    - disk_space
    - load
    - vcsreplicator_consumer_lag
    - vcsreplicator_processes
