---
# In the worst case, WSGI processes are CPU bound. Running more workers than
# available CPU cores could cause excessive context switching / thrashing
# and lower overall server throughput. However, our CPU utilization data shows
# that servers are nowhere close to CPU capacity when WSGI process count is
# equivalent to CPU core count. So, we run more WSGI processes than cores.
wsgi_processes: "{{ ansible_processor_vcpus * 2 }}"
httpd_start_servers: 8
httpd_min_spare_servers: 5
httpd_max_spare_servers: 20
# Run a few more httpd workers than WSGI workers so requests are available
# to be serviced once a WSGI worker is free.
httpd_server_limit: "{{ (ansible_processor_vcpus * 2.2)|round|int }}"
httpd_max_clients: "{{ (ansible_processor_vcpus * 2.2)|round|int }}"
httpd_max_requests_per_child: 4000

# Used for replication
mirror_source: hg.mozilla.org
mirror_ssh_user: vcs-sync@mozilla.com
mirror_ips: []
mirror_host_key: "undefined"
mirror_private_key: "undefined"

# Assume the chroot files aren't available unless told otherwise (since
# it is uncommon to deploy them).
chroot_mozbuild_exists: False

# Bloxtool connection settings (so we can retrieve Mozilla office IPs).
# Actual values will get pulled in from secrets.
bloxtool_user: bloxtool_user
bloxtool_password: bloxtool_password
bloxtool_url: https://bloxtool

s3_cache_access_key_id: dummy_aws_access_key_id
s3_cache_secret_key: dummy_aws_secret_key
s3_cache_bucket: moz-hg-wireproto-cache-testing
s3_cache_region: us-west-1
s3_cache_redirect_targets: https://s3-us-west-1.amazonaws.com/moz-hg-wireproto-cache-testing/
